# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# 文字列の長さ
Layout/LineLength:
  Max: 100

# メソッドの行数
# Metrics/MethodLength:
#  Max: 20

# 基準値を超えた警告
#Metrics/AbcSize:
#  Enabled: true
#  Max: 20

#versionupによって指定
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Rails/HelperInstanceVariable:
  Enabled: false
