version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn_rails -p 3000 -c /var/www/rails/unknownmusic/config/unicorn.conf.rb
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/var/www/rails/unknownmusic:cached
      #ソケット通信用ファイルをnginxコンテナと共有
      - tmp-data:/var/www/rails/unknownmusic/tmp/sockets
      #画像データをnginxと共有
      - public-data:/var/www/rails/unknownmusic/public

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: unknownmusic_development
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    #dbのデータを永続化しておく
    volumes:
      - mysql-data:/var/lib/mysql

  test-db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: unknownmusic_test
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - tmp-data:/var/www/rails/unknownmusic/tmp/sockets
      - public-data:/var/www/rails/unknownmusic/public
    depends_on:
      - web

volumes:
  public-data:
  tmp-data:
  mysql-data:
