version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -p 3000 -c /var/www/rails/unknownmusic/config/unicorn.conf.rb
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/rails/unknownmusic:cached
      #ソケット通信用ファイルをnginxコンテナと共有
      - tmp-data:/var/www/rails/unknownmusic/tmp/sockets
      #画像データとかをnginxと共有
      - public-data:/var/www/rails/unknownmusic/public

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kazuho
      MYSQL_PASSWORD: password
    #dbのデータを永続化しておく
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/var/www/rails/unknownmusic/tmp/sockets
      - public-data:/var/www/rails/unknownmusic/public
    depends_on:
      - web

volumes:
  public-data:
  tmp-data:
  mysql-data:
